name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Black
        uses: psf/black@stable
        continue-on-error: true
        
      - name: Check for changes
        id: git-check
        run: |
          echo "::set-output name=changed::$(git status --porcelain)"
          
      - name: Commit formatting changes
        run: |
          git config --global user.name 'Camreyn'
          git config --global user.email 'fathergestalt@gmail.com'
          git add -u
          git commit -m "Apply black formatting"
