name: Python Formatting

on: [pull_request]

jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - uses: psf/black@22.12.0
      with:
        version: "22.12.0"
        src: backend
        
    - name: Install black 22.12.0
      run: pip install black==22.12.0
    
    - name: Run black
      run: black --check .
    
    - name: Commit changes
      if: ${{ steps.black.outputs.is_changed == 'true' }}
      run: |
        git config --global user.name 'Camreyn'
        git config --global user.email 'fathergestalt@gmail.com'
        git commit -am "Apply black formatting"
        git push
